<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AbasSubDomainsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('abas_sub_domains')->delete();
        
        \DB::table('abas_sub_domains')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'مهارات التواصل',
                'name_en' => 'Communication',
                'abas_domain_id' => 1,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:01:13',
                'updated_at' => '2023-09-18 09:21:13',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'com',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'التوجه المجتمعي',
                'name_en' => 'Community Use',
                'abas_domain_id' => 3,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:01:23',
                'updated_at' => '2023-09-18 09:49:32',
                'description' => 'لا تقم بتطبيق مجال التوجه المجتمعي إذا كان عمر الطفل الذي يتم تقييمه أقل من عام واحد.',
                'description_en' => 'Do not complete this skill area if the child being rated is younger than 1 year old.',
                'code' => 'cu',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'الوظيفية قبل الأكاديمية',
                'name_en' => 'Functional Pre-Academics',
                'abas_domain_id' => 1,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:01:31',
                'updated_at' => '2023-09-18 09:50:52',
                'description' => 'لا تقم بتطبيق مجال المهارات الوظيفية قبل الأكاديمية  إذا كان عمر الطفل الذي يتم تقييمه أقل من عام واحد.',
                'description_en' => 'Do not complete this skill area if the child being rated is younger than 1 year old.',
                'code' => 'fa',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'المهارات المنزلية',
                'name_en' => 'Home Living',
                'abas_domain_id' => 3,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:01:39',
                'updated_at' => '2023-09-18 09:50:22',
                'description' => 'لا تقم بتطبيق مجال المهارات المنزلية إذا كان عمر الطفل الذي يتم تقييمه أقل من عام واحد.',
                'description_en' => 'Do not complete this skill area if the child being rated is younger than 1 year old.',
                'code' => 'hl',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'الصحة و السلامة',
                'name_en' => 'Health and Safety',
                'abas_domain_id' => 3,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:01:47',
                'updated_at' => '2023-09-18 09:43:01',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'hs',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'وقت الفراغ',
                'name_en' => 'Leisure',
                'abas_domain_id' => 2,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:01:56',
                'updated_at' => '2023-09-18 09:43:57',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'ls',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'الرعاية الذاتية',
                'name_en' => 'Self-Care',
                'abas_domain_id' => 3,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:02:03',
                'updated_at' => '2023-09-18 09:43:07',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sc',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'التوجيه الذاتي',
                'name_en' => 'Self-Direction',
                'abas_domain_id' => 1,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:02:12',
                'updated_at' => '2023-09-18 09:43:18',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sd',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'المهارات الاجتماعية',
                'name_en' => 'Social',
                'abas_domain_id' => 2,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:02:18',
                'updated_at' => '2023-09-18 09:46:10',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'soc',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'المهارات الحركية',
                'name_en' => 'Motor',
                'abas_domain_id' => NULL,
                'category' => 'parent_0_71',
                'created_at' => '2023-08-22 19:02:26',
                'updated_at' => '2023-09-18 09:43:38',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'mo',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'مهارات التواصل',
                'name_en' => 'Communication',
                'abas_domain_id' => 1,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:02:43',
                'updated_at' => '2023-09-18 09:44:06',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'com',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'التوجه المجتمعي',
                'name_en' => 'Community Use Ability Frequency',
                'abas_domain_id' => 3,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:02:52',
                'updated_at' => '2023-09-18 09:44:15',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'cu',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'الوظيفية الأكاديمية',
                'name_en' => 'Functional Academics',
                'abas_domain_id' => 1,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:07',
                'updated_at' => '2023-09-18 09:51:22',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'fa',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'المهارات المنزلية',
                'name_en' => 'Home Living',
                'abas_domain_id' => 3,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:14',
                'updated_at' => '2023-09-18 09:44:26',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'hl',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'الصحة و السلامة',
                'name_en' => 'Health and Safety',
                'abas_domain_id' => 3,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:21',
                'updated_at' => '2023-09-18 09:44:31',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'hs',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'وقت الفراغ',
                'name_en' => 'Leisure',
                'abas_domain_id' => 2,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:28',
                'updated_at' => '2023-09-18 09:44:39',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'ls',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'الرعاية الذاتية',
                'name_en' => 'Self-Care',
                'abas_domain_id' => 3,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:33',
                'updated_at' => '2023-09-18 09:44:46',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sc',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'التوجيه الذاتي',
                'name_en' => 'Self-Direction',
                'abas_domain_id' => 1,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:39',
                'updated_at' => '2023-09-18 09:44:53',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sd',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'المهارات الاجتماعية',
                'name_en' => 'Social',
                'abas_domain_id' => 2,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:46',
                'updated_at' => '2023-09-18 09:45:24',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'soc',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'مهارات العمل',
                'name_en' => 'Work',
                'abas_domain_id' => NULL,
                'category' => 'parent_72_263',
                'created_at' => '2023-08-22 19:03:55',
                'updated_at' => '2023-09-18 09:52:06',
                'description' => 'طبق مجال مهارات العمل إذا كان الفرد -المفحوص- الذي يتم تقييمه يعمل بدوام جزئي أو بدوام كامل.',
                'description_en' => 'Complete this skill area if the individual being rated holds a part-time or full-time job.',
                'code' => 'wk',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'مهارات التواصل',
                'name_en' => 'Communication',
                'abas_domain_id' => 1,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:04:39',
                'updated_at' => '2023-09-18 09:46:38',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'com',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'وظيفية قبل الأكاديميين',
                'name_en' => 'Functional Pre-Academics',
                'abas_domain_id' => 1,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:05:25',
                'updated_at' => '2023-09-18 09:46:45',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'fa',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'المهارات المدرسية',
                'name_en' => 'School Living',
                'abas_domain_id' => 3,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:05:39',
                'updated_at' => '2023-09-18 09:46:53',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sl',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'الصحة و السلامة',
                'name_en' => 'Health and Safety',
                'abas_domain_id' => 3,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:05:46',
                'updated_at' => '2023-09-18 09:46:59',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'hs',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'وقت الفراغ',
                'name_en' => 'Leisure',
                'abas_domain_id' => 2,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:05:54',
                'updated_at' => '2023-09-18 09:46:34',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'ls',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'الرعاية الذاتية',
                'name_en' => 'Self-Care',
                'abas_domain_id' => 3,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:06:01',
                'updated_at' => '2023-09-18 09:46:42',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sc',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'التوجيه الذاتي',
                'name_en' => 'Self-Direction',
                'abas_domain_id' => 1,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:06:11',
                'updated_at' => '2023-09-18 09:44:47',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sd',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'المهارات الاجتماعية',
                'name_en' => 'Social',
                'abas_domain_id' => 2,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:06:22',
                'updated_at' => '2023-09-18 09:44:34',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'soc',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'المهارات الحركية',
                'name_en' => 'Motor',
                'abas_domain_id' => NULL,
                'category' => 'teacher_caregiver_24_71',
                'created_at' => '2023-08-22 19:06:30',
                'updated_at' => '2023-09-18 09:44:27',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'mo',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'مهارات التواصل',
                'name_en' => 'Communication',
                'abas_domain_id' => 1,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:06:49',
                'updated_at' => '2023-09-18 09:44:21',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'com',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'التوجه المجتمعي',
                'name_en' => 'Community Use',
                'abas_domain_id' => 3,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:06:56',
                'updated_at' => '2023-09-18 09:44:10',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'cu',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'وظيفية أكاديمية',
                'name_en' => 'Functional Academics',
                'abas_domain_id' => 1,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:04',
                'updated_at' => '2023-09-18 09:44:03',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'fa',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'المهارات المدرسية',
                'name_en' => 'School Living',
                'abas_domain_id' => 3,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:12',
                'updated_at' => '2023-09-18 09:43:54',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sl',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'الصحة و السلامة',
                'name_en' => 'Health and Safety',
                'abas_domain_id' => 3,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:18',
                'updated_at' => '2023-09-18 09:31:11',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'HS',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'وقت الفراغ',
                'name_en' => 'Leisure',
                'abas_domain_id' => 2,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:25',
                'updated_at' => '2023-09-18 09:43:47',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'ls',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'الرعاية الذاتية',
                'name_en' => 'Self-Care',
                'abas_domain_id' => 3,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:32',
                'updated_at' => '2023-09-18 09:43:41',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sc',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'التوجيه الذاتي',
                'name_en' => 'Self-Direction',
                'abas_domain_id' => 1,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:39',
                'updated_at' => '2023-09-18 09:43:35',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'sd',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'المهارات الاجتماعية',
                'name_en' => 'Social',
                'abas_domain_id' => 2,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:46',
                'updated_at' => '2023-09-18 09:43:28',
                'description' => NULL,
                'description_en' => NULL,
                'code' => 'soc',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'مهارات العمل',
                'name_en' => 'Work',
                'abas_domain_id' => NULL,
                'category' => 'teacher_60_263',
                'created_at' => '2023-08-22 19:07:53',
                'updated_at' => '2023-09-18 09:52:12',
                'description' => 'طبق مجال مهارات العمل إذا كان الفرد -المفحوص- الذي يتم تقييمه يعمل بدوام جزئي أو بدوام كامل.',
                'description_en' => 'Complete the Work skill area if the individual being rated holds a part-time or full-time job.',
                'code' => 'wk',
            ),
        ));
        
        
    }
}